package ups.edu.ec.evaluacion;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2022-02-01T13:34:16.348-05:00
 * Generated source version: 3.5.0
 *
 */
@WebService(targetNamespace = "http://bean.evaluacion.ec.edu.ups/", name = "ContactosSeviceSOAp")
@XmlSeeAlso({ObjectFactory.class})
public interface ContactosSeviceSOAp {

    @WebMethod
    @RequestWrapper(localName = "crearVehi", targetNamespace = "http://bean.evaluacion.ec.edu.ups/", className = "ups.edu.ec.evaluacion.CrearVehi")
    @ResponseWrapper(localName = "crearVehiResponse", targetNamespace = "http://bean.evaluacion.ec.edu.ups/", className = "ups.edu.ec.evaluacion.CrearVehiResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String crearVehi(

        @WebParam(name = "arg0", targetNamespace = "")
        ups.edu.ec.evaluacion.Vehiculo arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getVehi", targetNamespace = "http://bean.evaluacion.ec.edu.ups/", className = "ups.edu.ec.evaluacion.GetVehi")
    @ResponseWrapper(localName = "getVehiResponse", targetNamespace = "http://bean.evaluacion.ec.edu.ups/", className = "ups.edu.ec.evaluacion.GetVehiResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ups.edu.ec.evaluacion.Vehiculo> getVehi()
;
}
