package ups.edu.ec.evaluacion;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2022-02-01T13:34:16.362-05:00
 * Generated source version: 3.5.0
 *
 */
@WebServiceClient(name = "ContactosSeviceSOApService",
                  wsdlLocation = "http://localhost:8080/Eva-PaguayLuisDavid-SRV/ContactosSeviceSOAp?wsdl",
                  targetNamespace = "http://bean.evaluacion.ec.edu.ups/")
public class ContactosSeviceSOApService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://bean.evaluacion.ec.edu.ups/", "ContactosSeviceSOApService");
    public final static QName ContactosSeviceSOApPort = new QName("http://bean.evaluacion.ec.edu.ups/", "ContactosSeviceSOApPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/Eva-PaguayLuisDavid-SRV/ContactosSeviceSOAp?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ContactosSeviceSOApService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/Eva-PaguayLuisDavid-SRV/ContactosSeviceSOAp?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ContactosSeviceSOApService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ContactosSeviceSOApService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ContactosSeviceSOApService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ContactosSeviceSOApService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ContactosSeviceSOApService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ContactosSeviceSOApService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ContactosSeviceSOAp
     */
    @WebEndpoint(name = "ContactosSeviceSOApPort")
    public ContactosSeviceSOAp getContactosSeviceSOApPort() {
        return super.getPort(ContactosSeviceSOApPort, ContactosSeviceSOAp.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ContactosSeviceSOAp
     */
    @WebEndpoint(name = "ContactosSeviceSOApPort")
    public ContactosSeviceSOAp getContactosSeviceSOApPort(WebServiceFeature... features) {
        return super.getPort(ContactosSeviceSOApPort, ContactosSeviceSOAp.class, features);
    }

}
